import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage3Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required for GENERATION)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: '3f3f3a43-bdf2-4d08-94f7-c82e2de5fdc9',
    description: 'Image 3 row ID (required for REFINE)',
  })
  @IsOptional()
  @IsUUID()
  imageId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for initial image, REFINE for versioned refinement',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Style template',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'A family picnic in bright daylight',
    description: 'Lifestyle scenario',
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  scenario?: string;

  @ApiPropertyOptional({
    example: 'Make the product bigger and add warmer tones',
    description: 'Required for REFINE mode',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
