import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateIf,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage7Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiProperty({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required)',
  })
  @ValidateIf((o: CreateImage7Dto) => Boolean(o.mode))
  @IsUUID()
  projectId!: string;

  @ApiProperty({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description: 'Mode enum: GENERATION | REFINE',
  })
  @IsEnum(ImageRequestMode)
  mode!: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 7 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiProperty({
    example: 'Emotional',
    description: 'Closing emotion direction',
  })
  @IsString()
  @MaxLength(120)
  direction!: string;

  @ApiProperty({
    example: 'Hydrate Better, Live Better',
    description: 'Closing headline text',
  })
  @IsString()
  @MaxLength(300)
  headline!: string;

  @ApiPropertyOptional({
    example: 'Make the closing message more premium and concise',
    description: 'Required when mode=REFINE',
  })
  @ValidateIf((o: CreateImage7Dto) => o.mode === ImageRequestMode.REFINE)
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
