import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage6Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required for GENERATION and REFINE)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: '8b68f28e-a4be-4218-aa8c-ac5d26cbca17',
    description: 'Image 6 row ID (required for REFINE)',
  })
  @IsOptional()
  @IsUUID()
  imageId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 6 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiProperty({
    type: [String],
    example: ['Insulated Mug', 'Travel Flask', 'Bottle Brush'],
    description: 'Cross-selling product names sent to AI',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(6)
  @IsString({ each: true })
  @MaxLength(300, { each: true })
  productNames!: string[];

  @ApiPropertyOptional({
    example: 'Make product 1 more prominent and simplify labels',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
