import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateIf,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage2Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiProperty({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required)',
  })
  @ValidateIf((o: CreateImage2Dto) => Boolean(o.mode))
  @IsUUID()
  projectId!: string;

  @ApiProperty({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description: 'Mode enum: GENERATION | REFINE',
  })
  @IsEnum(ImageRequestMode)
  mode!: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 2 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'Minimal',
    description: 'Background style for Image 2',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  backgroundStyle?: string;

  @ApiPropertyOptional({
    example: 'Top',
    description: 'Brand logo position',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  logoPosition?: string;

  @ApiProperty({ example: 'Leakproof lid' })
  @IsString()
  @MaxLength(300)
  keyFact1!: string;

  @ApiProperty({ example: 'BPA-free material' })
  @IsString()
  @MaxLength(300)
  keyFact2!: string;

  @ApiProperty({ example: '24h cold' })
  @IsString()
  @MaxLength(300)
  keyFact3!: string;

  @ApiProperty({ example: 'Ergonomic grip' })
  @IsString()
  @MaxLength(300)
  keyFact4!: string;

  @ApiPropertyOptional({
    example: 'Increase emphasis on key fact 1 and improve text hierarchy',
    description: 'Required when mode=REFINE',
  })
  @ValidateIf((o: CreateImage2Dto) => o.mode === ImageRequestMode.REFINE)
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
