import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateIf,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage1Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiProperty({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required)',
  })
  @IsUUID()
  projectId!: string;

  @ApiProperty({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description: 'Mode enum: GENERATION | REFINE',
  })
  @IsEnum(ImageRequestMode)
  mode!: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'clean-white-background',
    description: 'Optional style template for Image 1 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'Make product larger and improve shadow softness',
    description: 'Required when mode=REFINE',
  })
  @ValidateIf((o: CreateImage1Dto) => o.mode === ImageRequestMode.REFINE)
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    type: 'string',
    format: 'binary',
    description:
      'Main product image file. Required when mode=GENERATION, ignored for REFINE.',
  })
  @IsOptional()
  image?: unknown;
}
