import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';
import { ProjectContextDto } from './project-context.dto';

export class CreateImage3Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required for GENERATION)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for initial image, REFINE for versioned refinement',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Style template',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'A family picnic in bright daylight',
    description: 'Lifestyle scenario',
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  scenario?: string;

  @ApiPropertyOptional({
    example: 'Make the product bigger and add warmer tones',
    description: 'Required for REFINE mode',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    example:
      'https://sam-app-storage-eu.s3.eu-central-1.amazonaws.com/projects/lifestyle-refs/sample.png',
    description:
      'Reference image URL. Required for REFINE mode; GENERATION gets this from uploaded file.',
  })
  @IsOptional()
  @IsUrl()
  refImageUrl?: string;

  @ApiPropertyOptional({
    type: () => ProjectContextDto,
    description:
      'Project context object used for REFINE payload to AI. Should include project id as `id`.',
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => ProjectContextDto)
  projectContext?: ProjectContextDto;
}
