import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage7Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required for GENERATION and REFINE)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'b38513d3-e748-48ac-8f1c-62eaf1988dc8',
    description: 'Image 7 row ID (required for REFINE)',
  })
  @IsOptional()
  @IsUUID()
  imageId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 7 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiProperty({
    example: 'Emotional',
    description: 'Closing emotion direction',
  })
  @IsString()
  @MaxLength(120)
  direction!: string;

  @ApiProperty({
    example: 'Hydrate Better, Live Better',
    description: 'Closing headline text',
  })
  @IsString()
  @MaxLength(300)
  headline!: string;

  @ApiPropertyOptional({
    example: 'Make the closing message more premium and concise',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
