import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';
import { ProjectContextDto } from './project-context.dto';

export class CreateImage4Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description:
      'Optional legacy project ID. Preferred source is projectContext.id.',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 4 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiProperty({
    type: [String],
    example: ['Leakproof lid', 'BPA-free', 'Fast charge', '2-year warranty'],
    description: 'USP highlights sent to AI',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(4)
  @IsString({ each: true })
  @MaxLength(300, { each: true })
  usps!: string[];

  @ApiPropertyOptional({
    example: 'Make the first USP more prominent and reduce text size',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    type: () => ProjectContextDto,
    description:
      'Project context object for AI payload. Include `id` in both GENERATION and REFINE.',
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => ProjectContextDto)
  projectContext?: ProjectContextDto;
}
