import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage4Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required for GENERATION)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: '993035a4-52f4-46fe-a7a9-9a3c3cf0f3f0',
    description: 'Image 4 row ID (required for REFINE)',
  })
  @IsOptional()
  @IsUUID()
  imageId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 4 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiProperty({
    type: [String],
    example: ['Leakproof lid', 'BPA-free', 'Fast charge', '2-year warranty'],
    description: 'USP highlights sent to AI',
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(4)
  @IsString({ each: true })
  @MaxLength(300, { each: true })
  usps!: string[];

  @ApiPropertyOptional({
    example: 'Make the first USP more prominent and reduce text size',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;
}
