import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateIf,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';

export class CreateImage3Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiProperty({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description: 'Project ID (required)',
  })
  @ValidateIf((o: CreateImage3Dto) => Boolean(o.mode))
  @IsUUID()
  projectId!: string;

  @ApiProperty({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description: 'Mode enum: GENERATION | REFINE',
  })
  @IsEnum(ImageRequestMode)
  mode!: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Style template',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'A family picnic in bright daylight',
    description: 'Lifestyle scenario',
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  scenario?: string;

  @ApiPropertyOptional({
    example: 'Make the product bigger and add warmer tones',
    description: 'Required for REFINE mode',
  })
  @ValidateIf((o: CreateImage3Dto) => o.mode === ImageRequestMode.REFINE)
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    type: 'string',
    format: 'binary',
    description:
      'Lifestyle provider image file. Required when mode=GENERATION.',
  })
  @IsOptional()
  image?: unknown;
}
