import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ImageRequestMode } from './image-request-mode.enum';
import { ProjectContextDto } from './project-context.dto';

export class CreateImage2Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description:
      'Project ID (required for GENERATION, optional for REFINE if projectContext.id is provided)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'playful',
    description: 'Optional style template for Image 2 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'Minimal',
    description: 'Background style for Image 2',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  backgroundStyle?: string;

  @ApiPropertyOptional({
    example: 'Top',
    description: 'Brand logo position',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  logoPosition?: string;

  @ApiProperty({ example: 'Leakproof lid' })
  @IsString()
  @MaxLength(300)
  keyFact1!: string;

  @ApiProperty({ example: 'BPA-free material' })
  @IsString()
  @MaxLength(300)
  keyFact2!: string;

  @ApiProperty({ example: '24h cold' })
  @IsString()
  @MaxLength(300)
  keyFact3!: string;

  @ApiProperty({ example: 'Ergonomic grip' })
  @IsString()
  @MaxLength(300)
  keyFact4!: string;

  @ApiPropertyOptional({
    example: 'Increase emphasis on key fact 1 and improve text hierarchy',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    example:
      'https://sam-app-storage-eu.s3.eu-central-1.amazonaws.com/projects/generated/image2/sample.png',
    description:
      'Optional previous generated image URL for refine (not required by AI screenshot, but supported)',
  })
  @IsOptional()
  @IsUrl()
  imageUrl?: string;

  @ApiPropertyOptional({
    type: () => ProjectContextDto,
    description:
      'Project context object used for REFINE payload to AI. Should include project id as `id`.',
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => ProjectContextDto)
  projectContext?: ProjectContextDto;
}
