import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsOptional,
  IsString,
  IsUrl,
  IsUUID,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import { ImageRequestMode } from './image-request-mode.enum';
import { ProjectContextDto } from './project-context.dto';

export class CreateImage1Dto {
  @ApiProperty({
    example: '9f1f2f6a-3fbb-4421-9287-09f4571d65aa',
    description: 'Unique key generated by frontend per action/retry group',
  })
  @IsString()
  @MaxLength(120)
  idempotencyKey!: string;

  @ApiPropertyOptional({
    format: 'uuid',
    example: 'f0c02bd3-e90f-4fdc-9f3f-13f4cc4a1f58',
    description:
      'Project ID (required for GENERATION, optional for REFINE if projectContext.id is provided)',
  })
  @IsOptional()
  @IsUUID()
  projectId?: string;

  @ApiPropertyOptional({
    enum: ImageRequestMode,
    default: ImageRequestMode.GENERATION,
    description:
      'GENERATION for first render, REFINE for versioned refine flow',
  })
  @IsOptional()
  @IsEnum(ImageRequestMode)
  mode?: ImageRequestMode;

  @ApiPropertyOptional({
    example: 'clean-white-background',
    description: 'Optional style template for Image 1 generation',
  })
  @IsOptional()
  @IsString()
  @MaxLength(200)
  style?: string;

  @ApiPropertyOptional({
    example: 'Make product larger and improve shadow softness',
    description: 'Required when mode=REFINE',
  })
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  feedback?: string;

  @ApiPropertyOptional({
    example:
      'https://sam-app-storage-eu.s3.eu-central-1.amazonaws.com/projects/generated/image1/sample.png',
    description: 'Previous generated image URL (required when mode=REFINE)',
  })
  @IsOptional()
  @IsUrl()
  imageUrl?: string;

  @ApiPropertyOptional({
    type: () => ProjectContextDto,
    description:
      'Project context object used for REFINE payload to AI. Should include project id as `id`.',
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => ProjectContextDto)
  projectContext?: ProjectContextDto;
}
